
baseurl = "https://allthebacteria.org/"
enablerobotstxt = true
titlecasestyle = "Go"

[languages.en]
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
title = "AllTheBacteria"
weight = 10

[languages.en.params.paige.site]
description = "All bacterial genomes assembled, available and searchable"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github"
[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[[module.mounts]]
source = "paige/node_modules/bootstrap-icons/font/fonts"
target = "static/css/paige/bootstrap-icons/fonts"
[[module.mounts]]
source = "paige/node_modules/bootstrap-icons/font"
target = "assets/css/paige/bootstrap-icons"

[paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.pages.base_schema]
isAccessibleForFree = true
isFamilyFriendly = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true
disable_tags = true

[paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"